# https://assets.nagios.com/downloads/nagiosxi/docs/Offloading_MySQL_to_Remote%20Server.pdf
# https://support.nagios.com/kb/article/nagios-xi-strict_trans_tables-780.html
---

- name: install python3-PyMySQL
  pip:
    name: PyMySQL

- name: checking if db tables exist
  mysql_query:
    login_user: root
    login_host: "{{ nagios_db_host }}"
    login_password: "{{ nagios_db_root_password }}"
    query:
    - "SELECT count(*) as value FROM information_schema.tables WHERE table_schema='{{ item }}';"
  no_log: true
  register: _nagiosdb
  with_items: "{{ nagios_db_databases }}"

- name: set_fact _nagiosdbs
  set_fact:
    _nagiosdbs: "{{ _nagiosdbs|default({}) | combine( { item.item: item.query_result[0][0]['value'] } ) }}"
  with_items: "{{ _nagiosdb.results }}"
  no_log: yes

- include: database_tasks.yml
  when: _nagiosdbs is defined and _nagiosdbs.nagios<1
