---

- name: Check the nagios exists
  stat:
    path: /usr/local/nagioss
  register: stat_result

- name: perform (non-interactive) full install
  command: ./fullinstall -n
  args:
    chdir: /tmp/nagiosxi
    creates: /usr/local/nagios
  when: not stat_result.stat.exists and nagios_db_root_passwd is not defined

- name: msg
  debug:
    msg: 'to following the install/upgrade: tail -f /tmp/nagiosxi/install.log'

- name: perform (non-interactive) full install
  command:
    argv:
      - ./fullinstall 
      - -n
      - --mysql-password 
      - "{{ nagios_db_root_passwd }}"
  args:
    chdir: /tmp/nagiosxi
    creates: /usr/local/nagios
  when: not stat_result.stat.exists and nagios_db_root_passwd is defined

- name: perform (non-interactive) full upgrade
  command: ./upgrade -n
  args:
    chdir: /tmp/nagiosxi
  when: nagios_upgrade
